### ISSUE TITLE
M5Flow V1.7.4 on core2 - slider get_value() maxes out at 100

### ISSUE THREAD

**Issue by EdgarBarranco** [m5stack/UiFlow-Bug-Report#66] opened 2021-03-27 19:08 UTC
Hi,

I set the min and max value from 0 to 255, but when the slider is all the way to the right, the maximum value it returns is 100, not 254.

`slider_b = M5Slider(x=55, y=175, w=230, h=10, min=0, max=255, bg_c=0xa0a0a0, color=0x0000ff, parent=None)`

but 

`LED_B = slider_b.get_value() `

Sets LED_B to 100 when is all the way to the right, I was expecting 255.

**Comment by imliubo** [comment] 2021-06-04 09:05
Hi @EdgarBarranco ,
This problem has been fixed in v1.7.8, please reburner and try. 
Have a nice day.
 Please feel free to reopen if the issue is not resolved to your satisfaction.

**Closed by imliubo** 2021-06-04 09:05 UTC
